targets:
  $default:
    sources:
      include:
        - lib/**
        - $package$
      exclude:
        - example/**
        - "**/*.g.dart"
        - "**/*.freezed.dart"
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - example/**/*.dart
